### ISSUE TITLE
getting error java.lang.ThreadLocal.get() null please help

### ISSUE THREAD

**Issue by govinda-rai** [rajatt95/Final_Framework_Selenium_TestNG#1]
<img width="544" alt="image" src="https://user-images.githubusercontent.com/130759525/233819879-82180480-6c45-437d-9044-af70096cd5a3.png">

**Comment by rajatt95** [comment]
Hi Govind,
Good morning!

Please refer the below automation framework:
1. https://github.com/rajatt95/MasterSeleniumFramework
2. https://github.com/rajatt95/MasterSeleniumFramework_BDD
